Enabling script after directory change
leongross/caliptra-sw pull request #39
Opened 2023-12-05 16:42 UTC by jlmahowa-amd

2023-12-05 17:13 UTC, leongross requested changes

2023-12-05 17:13 UTC, leongross commented on hw-latest/fpga/setup_fpga.sh
> +CALIPTRA_ROOT=$(realpath $(dirname "$( readlink -f -- "$0"; )")/../../)
To prevent potential word splitting (SC2046) this should be quoted.

```suggestion
CALIPTRA_ROOT=$(realpath "$(dirname "$( readlink -f -- "$0"; )")"/../../)
```

2023-12-05 17:13 UTC, leongross commented on hw-latest/fpga/setup_fpga.sh
> +    if [ ! -d /sys/class/gpio/gpio321 ]
```suggestion
    if [[ ! -d /sys/class/gpio/gpio321 ]]
```

2023-12-05 17:13 UTC, leongross commented on hw-latest/fpga/setup_fpga.sh
> +    if ! lsmod | grep -wq rom_backdoor; then
Checking if the module is loaded is a good idea, but for readability the coding style should be consistent, so testing the expression using `[[ ... ]]]`

2023-12-05 17:13 UTC, leongross commented on hw-latest/fpga/setup_fpga.sh
> +    if ! lsmod | grep -wq io_module; then
Same here

2023-12-05 17:13 UTC, leongross commented on hw-latest/fpga/setup_fpga.sh
> +    if ! lsmod | grep -wq io_module; then
```suggestion
    if ! lsmod | grep -wq "io_module"; then
```

2023-12-05 17:13 UTC, leongross commented on hw-latest/fpga/setup_fpga.sh
> +    if ! lsmod | grep -wq rom_backdoor; then
```suggestion
    if ! lsmod | grep -wq "rom_backdoor"; then
```

2023-12-06 16:55 UTC, jlmahowa-amd commented on hw-latest/fpga/setup_fpga.sh
> +    if ! lsmod | grep -wq rom_backdoor; then
I've spent more time than I would like and I was unable to find a solution using [[..]]. If this is important to you I will leave it to you to fix.

2023-12-11 13:20 UTC, merged

2023-12-11 13:21 UTC, leongross commented
lgtm